### ISSUE TITLE
[Feature]: Jwt Authentication Implementation

### ISSUE THREAD

**Issue by ablankz** [cresplanex/bloader#13]
### 🚀 Feature Proposal
Jwt authentication has not been implemented and needs to be implemented.

- [ ] Determine implementation method (jwt is not as well defined as `oauth`, so it needs to be flexible)
- [ ] Definition description in config file
- [ ] Local execution only
- [ ] Define proto between master, slave
- [ ] Execution using Master+Slave
- [ ] Updating Documents

### ✨ Motivation
Jwt is one of the most commonly used authentication methods and must be supported.

### 📝 Additional Context
For response parsing (e.g. getting tokens), Extractor might be available as follows?

``` yaml
      extractor:
        type: "jmesPath"
        jmes_path: "data.token"
```
