### ISSUE TITLE
[Feature]: Add Action

### ISSUE THREAD

**Issue by ablankz** [cresplanex/bloader#39]
### 🚀 Feature Proposal
Flexibility should be increased by adding the following useful actions.
In particular, it would be even better if the threads that continue to move asynchronously could be subjected to some kind of action by an event.

```yaml
kind: Flow
step:
  concurrency: -1
  flows:
    - id: "import"
      type: file
      mkdir: false
      file: {{ printf "scenario/%s/store_import.yaml" .Values.Case }}
    - id: "slaveSetup"
      type: flow
      mkdir: false
      concurrency: 0
      flows:
        - id: "slaveMemory"
          type: file
          mkdir: false
          file: "slave/memory.yaml"
          values: []
          thread_only_values: []
        - id: "slaveConnect"
          type: file
          mkdir: false
          file: "slave/connect.yaml"
          values: []
          thread_only_values:
            - key: "SlaveCount"
              value: {{ .Values.SlaveCount }}
          # ------------------ Here ------------------
          actions:   
            - id: "disconnect"
              type: "disconnect"
              on:
                - event: "sys:terminated"
                  flow: "request"
    - id: {{ .Values.Case }}
      type: flow
      mkdir: true
      concurrency: -1
      depends_on:
        - flow: slaveConnect
          event: slaveConnect:connected
        - flow: import
          event: sys:terminated
      flows:
        - id: "metrics"
          type: file
          mkdir: true
          file: "metrics/main.yaml"
          values:
            - key: "MetricsInterval"
              value: "5s"
            - key: "MetricsBreakTime"
              value: "10m"
          thread_only_values: []
        - id: "request"
          type: file
          mkdir: true
          file: "request.yaml"
```

### ✨ Motivation
Significant increase in flexibility.
